### ISSUE TITLE
Plugin Assembly Binding Issue

### ISSUE THREAD

**Issue by J8K3-zz** [awslabs/aws-ms-deploy-assistant#3]
### Description

Several assembly binding issues have been reported for plugin assembly's loaded at runtime. 
### Steps to recreate
1. Execute tool attached to a project outside of development project.

**Comment by ghost** [comment]
I have the same issue... 


2017-02-01T14:46:58.8132513Z System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
2017-02-01T14:46:58.8142538Z    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
2017-02-01T14:46:58.8142538Z    at System.Reflection.Assembly.LoadFile(String path)
2017-02-01T14:46:58.8142538Z    at AWSDeploymentAssistant.Pipeline.RunPlugins()
2017-02-01T14:46:58.8142538Z    at AWSDeploymentAssistant.Pipeline.Run()
2017-02-01T14:46:58.8142538Z    at AWSDeploymentAssistant.Program.RunBuildReqeust(BuildRequest request) 

Try adding the following to the config file awsdeploymentassistant <loadFromRemoteSources enabled="true"/>    That will fix your problem with the assembly binding issue.

**Comment by briankavanaugh** [comment]
If you run the script listed under "Development Environment Setup", that takes care of both creating the various folders needed, and setting the correct permissions on the files for this project.

**Comment by briankavanaugh** [comment]
If you modify AWSDeploymentAssistant.exe.config as suggested in the link in the error to enable loadFromRemoteSources, then it works.

This is what the runtime section would look like after modifying it:

```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="bin;bin\plugins" />
    </assemblyBinding>
    <loadFromRemoteSources enabled="true"/>
  </runtime>
```
